#!/bin/bash
set -eu

declare HOST=$1
declare STATUS=$2
declare TIMEOUT=$3

HOST=$HOST STATUS=$STATUS timeout --foreground -s TERM $TIMEOUT bash -c \
    'while [[ ${STATUS_RECEIVED} != ${STATUS} ]];\
        do STATUS_RECEIVED=$(curl -s -o /dev/null -L -w ''%{http_code}'' ${HOST}) && \
        echo "Polling [$HOST].. Received status code: $STATUS_RECEIVED" && \
        sleep 1;\
    done;
    echo Success with status: $STATUS_RECEIVED'

